pull_request_rules:
  - name: Auto-merge Dependabot updates
    conditions:
      - base=main
      - author=dependabot[bot]
      - -draft
      - conflict=false
      - check-success=CI / ci
    actions:
      merge:
        method: squash
