name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔽
        uses: actions/checkout@v4
      - name: Setup UV 🔌
        uses: astral-sh/setup-uv@v7
      - name: Install Dependencies 📦
        run: uv sync
      - name: Setup Just 🔌
        uses: extractions/setup-just@v2
      - name: Lint 🤖
        run: just ci
      - name: Fetch Font 📄
        run: just fetch-font
      - name: Build Docker 🐳
        run: just build-docker